:FAM-HACKER_CLIENT
 REM                       ███████╗╔█████╗─███╗───███╗─██╗──██╗╔█████╗─╔██████╗██╗──██╗██████╗─
 REM                       ██╔════╝██╔══██╗████╗─████║─██║──██║██╔══██╗██╔════╝██║─██╔╝██╔══██╗─
 REM                       █████╗──███████║██╔████╔██║─███████║███████║██║─────█████╔╝─██████╔╝─
 REM                       ██╔══╝──██╔══██║██║╚██╔╝██║─██╔══██║██╔══██║██║─────██╔═██╗─██╔══██╗─
 REM                       ██║─────██║──██║██║─╚═╝─██║─██║──██║██║──██║╚██████╗██║──██╗██║──██║─
 REM                       ╚═╝─────╚═╝──╚═╝╚═╝─────╚═╝─╚═╝──╚═╝╚═╝──╚═╝─╚═════╝╚═╝──╚═╝╚═╝──╚═╝─
 REM                                ╔██████╗██╗─────██╗███████╗███╗───██╗████████╗─
 REM                                ██╔════╝██║─────██║██╔════╝████╗──██║╚══██╔══╝─
 REM                                ██║─────██║─────██║█████╗──██╔██╗─██║───██║─
 REM                                ██║─────██║─────██║██╔══╝──██║╚██╗██║───██║─
 REM                                ╚██████╗███████╗██║███████╗██║─╚████║───██║─
 REM                                 ╚═════╝╚══════╝╚═╝╚══════╝╚═╝──╚═══╝───╚═╝─
 REM                     ----------------------------Nah-Fam_Studios----------------------------
 REM
 REM                            This will return to the running file if all colors are set
@ECHO OFF
 IF /I "%~1"=="__COLOR_GOLDMINER_BLINK__" GOTO :COLOR_GOLDMINER_BLINK_ROUTINE
        SET "_COLORS_MISSING="
 IF NOT DEFINED COLOR_BLACK SET "_COLORS_MISSING=1"
 IF NOT DEFINED COLOR_BLUE SET "_COLORS_MISSING=1"
 IF NOT DEFINED COLOR_CYAN SET "_COLORS_MISSING=1"
 IF NOT DEFINED COLOR_GREEN SET "_COLORS_MISSING=1"
 IF NOT DEFINED COLOR_PURPLE SET "_COLORS_MISSING=1"
 IF NOT DEFINED COLOR_RED SET "_COLORS_MISSING=1"
 IF NOT DEFINED COLOR_WHITE SET "_COLORS_MISSING=1"
 IF NOT DEFINED COLOR_YELLOW SET "_COLORS_MISSING=1"
 IF NOT DEFINED COLOR_BRIGHTBLACK SET "_COLORS_MISSING=1"
 IF NOT DEFINED COLOR_BRIGHTBLUE SET "_COLORS_MISSING=1"
 IF NOT DEFINED COLOR_BRIGHTCYAN SET "_COLORS_MISSING=1"
 IF NOT DEFINED COLOR_BRIGHTGREEN SET "_COLORS_MISSING=1"
 IF NOT DEFINED COLOR_BRIGHTPURPLE SET "_COLORS_MISSING=1"
 IF NOT DEFINED COLOR_BRIGHTRED SET "_COLORS_MISSING=1"
 IF NOT DEFINED COLOR_BRIGHTWHITE SET "_COLORS_MISSING=1"
 IF NOT DEFINED COLOR_BRIGHTYELLOW SET "_COLORS_MISSING=1"
 IF NOT DEFINED COLOR_FBLK_BLACK SET "_COLORS_MISSING=1"
 IF NOT DEFINED COLOR_FBLK_BLUE SET "_COLORS_MISSING=1"
 IF NOT DEFINED COLOR_FBLK_CYAN SET "_COLORS_MISSING=1"
 IF NOT DEFINED COLOR_FBLK_GREEN SET "_COLORS_MISSING=1"
 IF NOT DEFINED COLOR_FBLK_PURPLE SET "_COLORS_MISSING=1"
 IF NOT DEFINED COLOR_FBLK_RED SET "_COLORS_MISSING=1"
 IF NOT DEFINED COLOR_FBLK_WHITE SET "_COLORS_MISSING=1"
 IF NOT DEFINED COLOR_FBLK_YELLOW SET "_COLORS_MISSING=1"
 IF NOT DEFINED COLOR_FBLK_BRIGHTBLACK SET "_COLORS_MISSING=1"
 IF NOT DEFINED COLOR_FBLK_BRIGHTBLUE SET "_COLORS_MISSING=1"
 IF NOT DEFINED COLOR_FBLK_BRIGHTCYAN SET "_COLORS_MISSING=1"
 IF NOT DEFINED COLOR_FBLK_BRIGHTGREEN SET "_COLORS_MISSING=1"
 IF NOT DEFINED COLOR_FBLK_BRIGHTPURPLE SET "_COLORS_MISSING=1"
 IF NOT DEFINED COLOR_FBLK_BRIGHTRED SET "_COLORS_MISSING=1"
 IF NOT DEFINED COLOR_FBLK_BRIGHTWHITE SET "_COLORS_MISSING=1"
 IF NOT DEFINED COLOR_FBLK_BRIGHTYELLOW SET "_COLORS_MISSING=1"
 IF NOT DEFINED COLOR_SLB_BLACK SET "_COLORS_MISSING=1"
 IF NOT DEFINED COLOR_SLB_BLUE SET "_COLORS_MISSING=1"
 IF NOT DEFINED COLOR_SLB_CYAN SET "_COLORS_MISSING=1"
 IF NOT DEFINED COLOR_SLB_GREEN SET "_COLORS_MISSING=1"
 IF NOT DEFINED COLOR_SLB_PURPLE SET "_COLORS_MISSING=1"
 IF NOT DEFINED COLOR_SLB_RED SET "_COLORS_MISSING=1"
 IF NOT DEFINED COLOR_SLB_WHITE SET "_COLORS_MISSING=1"
 IF NOT DEFINED COLOR_SLB_YELLOW SET "_COLORS_MISSING=1"
 IF NOT DEFINED COLOR_SLB_BRIGHTBLACK SET "_COLORS_MISSING=1"
 IF NOT DEFINED COLOR_SLB_BRIGHTBLUE SET "_COLORS_MISSING=1"
 IF NOT DEFINED COLOR_SLB_BRIGHTCYAN SET "_COLORS_MISSING=1"
 IF NOT DEFINED COLOR_SLB_BRIGHTGREEN SET "_COLORS_MISSING=1"
 IF NOT DEFINED COLOR_SLB_BRIGHTPURPLE SET "_COLORS_MISSING=1"
 IF NOT DEFINED COLOR_SLB_BRIGHTRED SET "_COLORS_MISSING=1"
 IF NOT DEFINED COLOR_SLB_BRIGHTWHITE SET "_COLORS_MISSING=1"
 IF NOT DEFINED COLOR_SLB_BRIGHTYELLOW SET "_COLORS_MISSING=1"
 IF NOT DEFINED COLOR_BG_BLACK SET "_COLORS_MISSING=1"
 IF NOT DEFINED COLOR_BG_BLUE SET "_COLORS_MISSING=1"
 IF NOT DEFINED COLOR_BG_CYAN SET "_COLORS_MISSING=1"
 IF NOT DEFINED COLOR_BG_GREEN SET "_COLORS_MISSING=1"
 IF NOT DEFINED COLOR_BG_PURPLE SET "_COLORS_MISSING=1"
 IF NOT DEFINED COLOR_BG_RED SET "_COLORS_MISSING=1"
 IF NOT DEFINED COLOR_BG_BLK_RED SET "_COLORS_MISSING=1"
 IF NOT DEFINED COLOR_BG_BLK2_RED SET "_COLORS_MISSING=1"
 IF NOT DEFINED COLOR_BG_WHITE SET "_COLORS_MISSING=1"
 IF NOT DEFINED COLOR_BG_YELLOW SET "_COLORS_MISSING=1"
 IF NOT DEFINED COLOR_RESET SET "_COLORS_MISSING=1"
 IF NOT DEFINED COLOR_GEMS SET "_COLORS_MISSING=1"
 IF NOT DEFINED COLOR_AQUA SET "_COLORS_MISSING=1"
 IF NOT DEFINED COLOR_DARK_GRAY SET "_COLORS_MISSING=1"
 IF NOT DEFINED COLOR_LIGHT_GRAY SET "_COLORS_MISSING=1"
 IF NOT DEFINED COLOR_DARK_GREEN SET "_COLORS_MISSING=1"
 IF NOT DEFINED COLOR_DEFAULT SET "_COLORS_MISSING=1"
 IF NOT DEFINED COLOR_ORANGE SET "_COLORS_MISSING=1"
 IF NOT DEFINED COLOR_BRIGHTORANGE SET "_COLORS_MISSING=1"
 IF NOT DEFINED COLOR_LOGO SET "_COLORS_MISSING=1"
 IF NOT DEFINED COLOR_BASICMINER SET "_COLORS_MISSING=1"
 IF NOT DEFINED COLOR_SILVERMINER SET "_COLORS_MISSING=1"
 IF NOT DEFINED COLOR_IRONMINER SET "_COLORS_MISSING=1"
 IF NOT DEFINED COLOR_GOLDMINER SET "_COLORS_MISSING=1"
 IF NOT DEFINED COLOR_GOLDMINER_BLINK SET "_COLORS_MISSING=1"
 IF NOT DEFINED COLOR_DIAMONDMINER SET "_COLORS_MISSING=1"
 IF NOT DEFINED COLOR_EMERALDMINER SET "_COLORS_MISSING=1"
 IF NOT DEFINED COLOR_DARKMATTERMINER SET "_COLORS_MISSING=1"

:
 IF NOT DEFINED _COLORS_MISSING EXIT /B 0
 SET "_COLORS_MISSING="

REM Only fill variables that are missing from the current CMD session.
REM SETX is used only when that variable is also missing from HKCU\Environment.

:BLACK
    IF NOT DEFINED COLOR_BLACK (
        SET "COLOR_BLACK=[30m"
        REG QUERY "HKCU\Environment" /V COLOR_BLACK>NUL 2>&1
        IF ERRORLEVEL 1 (
            SETX COLOR_BLACK "[30m" >NUL
        )
    )

:BLUE
    IF NOT DEFINED COLOR_BLUE (
        SET "COLOR_BLUE=[34m"
        REG QUERY "HKCU\Environment" /V COLOR_BLUE>NUL 2>&1
        IF ERRORLEVEL 1 (
            SETX COLOR_BLUE "[34m" >NUL
        )
    )

:CYAN
    IF NOT DEFINED COLOR_CYAN (
        SET "COLOR_CYAN=[36m"
        REG QUERY "HKCU\Environment" /V COLOR_CYAN>NUL 2>&1
        IF ERRORLEVEL 1 (
            SETX COLOR_CYAN "[36m" >NUL
        )
    )

:GREEN
    IF NOT DEFINED COLOR_GREEN (
        SET "COLOR_GREEN=[32m"
        REG QUERY "HKCU\Environment" /V COLOR_GREEN>NUL 2>&1
        IF ERRORLEVEL 1 (
            SETX COLOR_GREEN "[32m" >NUL
        )
    )

:PURPLE
    IF NOT DEFINED COLOR_PURPLE (
        SET "COLOR_PURPLE=[35m"
        REG QUERY "HKCU\Environment" /V COLOR_PURPLE>NUL 2>&1
        IF ERRORLEVEL 1 (
            SETX COLOR_PURPLE "[35m" >NUL
        )
    )

:RED
    IF NOT DEFINED COLOR_RED (
        SET "COLOR_RED=[31m"
        REG QUERY "HKCU\Environment" /V COLOR_RED>NUL 2>&1
        IF ERRORLEVEL 1 (
            SETX COLOR_RED "[31m" >NUL
        )
    )

:WHITE
    IF NOT DEFINED COLOR_WHITE (
        SET "COLOR_WHITE=[37m"
        REG QUERY "HKCU\Environment" /V COLOR_WHITE>NUL 2>&1
        IF ERRORLEVEL 1 (
            SETX COLOR_WHITE "[37m" >NUL
        )
    )

:YELLOW
    IF NOT DEFINED COLOR_YELLOW (
        SET "COLOR_YELLOW=[33m"
        REG QUERY "HKCU\Environment" /V COLOR_YELLOW>NUL 2>&1
        IF ERRORLEVEL 1 (
            SETX COLOR_YELLOW "[33m" >NUL
        )
    )

:BRIGHTBLACK
    IF NOT DEFINED COLOR_BRIGHTBLACK (
        SET "COLOR_BRIGHTBLACK=[1;30m"
        REG QUERY "HKCU\Environment" /V COLOR_BRIGHTBLACK>NUL 2>&1
        IF ERRORLEVEL 1 (
            SETX COLOR_BRIGHTBLACK "[1;30m" >NUL
        )
    )

:BRIGHTBLUE
    IF NOT DEFINED COLOR_BRIGHTBLUE (
        SET "COLOR_BRIGHTBLUE=[1;34m"
        REG QUERY "HKCU\Environment" /V COLOR_BRIGHTBLUE>NUL 2>&1
        IF ERRORLEVEL 1 (
            SETX COLOR_BRIGHTBLUE "[1;34m" >NUL
        )
    )

:BRIGHTCYAN
    IF NOT DEFINED COLOR_BRIGHTCYAN (
        SET "COLOR_BRIGHTCYAN=[1;36m"
        REG QUERY "HKCU\Environment" /V COLOR_BRIGHTCYAN>NUL 2>&1
        IF ERRORLEVEL 1 (
            SETX COLOR_BRIGHTCYAN "[1;36m" >NUL
        )
    )

:BRIGHTGREEN
    IF NOT DEFINED COLOR_BRIGHTGREEN (
        SET "COLOR_BRIGHTGREEN=[1;32m"
        REG QUERY "HKCU\Environment" /V COLOR_BRIGHTGREEN>NUL 2>&1
        IF ERRORLEVEL 1 (
            SETX COLOR_BRIGHTGREEN "[1;32m" >NUL
        )
    )

:BRIGHTPURPLE
    IF NOT DEFINED COLOR_BRIGHTPURPLE (
        SET "COLOR_BRIGHTPURPLE=[1;35m"
        REG QUERY "HKCU\Environment" /V COLOR_BRIGHTPURPLE>NUL 2>&1
        IF ERRORLEVEL 1 (
            SETX COLOR_BRIGHTPURPLE "[1;35m" >NUL
        )
    )

:BRIGHTRED
    IF NOT DEFINED COLOR_BRIGHTRED (
        SET "COLOR_BRIGHTRED=[1;31m"
        REG QUERY "HKCU\Environment" /V COLOR_BRIGHTRED>NUL 2>&1
        IF ERRORLEVEL 1 (
            SETX COLOR_BRIGHTRED "[1;31m" >NUL
        )
    )

:BRIGHTWHITE
    IF NOT DEFINED COLOR_BRIGHTWHITE (
        SET "COLOR_BRIGHTWHITE=[1;37m"
        REG QUERY "HKCU\Environment" /V COLOR_BRIGHTWHITE>NUL 2>&1
        IF ERRORLEVEL 1 (
            SETX COLOR_BRIGHTWHITE "[1;37m" >NUL
        )
    )

:BRIGHTYELLOW
    IF NOT DEFINED COLOR_BRIGHTYELLOW (
        SET "COLOR_BRIGHTYELLOW=[1;33m"
        REG QUERY "HKCU\Environment" /V COLOR_BRIGHTYELLOW>NUL 2>&1
        IF ERRORLEVEL 1 (
            SETX COLOR_BRIGHTYELLOW "[1;33m" >NUL
        )
    )

:FBLK_BLACK
    IF NOT DEFINED COLOR_FBLK_BLACK (
        SET "COLOR_FBLK_BLACK=[6;30m"
        REG QUERY "HKCU\Environment" /V COLOR_FBLK_BLACK>NUL 2>&1
        IF ERRORLEVEL 1 (
            SETX COLOR_FBLK_BLACK "[6;30m" >NUL
        )
    )

:FBLK_BLUE
    IF NOT DEFINED COLOR_FBLK_BLUE (
        SET "COLOR_FBLK_BLUE=[6;34m"
        REG QUERY "HKCU\Environment" /V COLOR_FBLK_BLUE>NUL 2>&1
        IF ERRORLEVEL 1 (
            SETX COLOR_FBLK_BLUE "[6;34m" >NUL
        )
    )

:FBLK_CYAN
    IF NOT DEFINED COLOR_FBLK_CYAN (
        SET "COLOR_FBLK_CYAN=[6;36m"
        REG QUERY "HKCU\Environment" /V COLOR_FBLK_CYAN>NUL 2>&1
        IF ERRORLEVEL 1 (
            SETX COLOR_FBLK_CYAN "[6;36m" >NUL
        )
    )

:FBLK_GREEN
    IF NOT DEFINED COLOR_FBLK_GREEN (
        SET "COLOR_FBLK_GREEN=[6;32m"
        REG QUERY "HKCU\Environment" /V COLOR_FBLK_GREEN>NUL 2>&1
        IF ERRORLEVEL 1 (
            SETX COLOR_FBLK_GREEN "[6;32m" >NUL
        )
    )

:FBLK_PURPLE
    IF NOT DEFINED COLOR_FBLK_PURPLE (
        SET "COLOR_FBLK_PURPLE=[6;35m"
        REG QUERY "HKCU\Environment" /V COLOR_FBLK_PURPLE>NUL 2>&1
        IF ERRORLEVEL 1 (
            SETX COLOR_FBLK_PURPLE "[6;35m" >NUL
        )
    )

:FBLK_RED
    IF NOT DEFINED COLOR_FBLK_RED (
        SET "COLOR_FBLK_RED=[6;31m"
        REG QUERY "HKCU\Environment" /V COLOR_FBLK_RED>NUL 2>&1
        IF ERRORLEVEL 1 (
            SETX COLOR_FBLK_RED "[6;31m" >NUL
        )
    )

:FBLK_WHITE
    IF NOT DEFINED COLOR_FBLK_WHITE (
        SET "COLOR_FBLK_WHITE=[6;37m"
        REG QUERY "HKCU\Environment" /V COLOR_FBLK_WHITE>NUL 2>&1
        IF ERRORLEVEL 1 (
            SETX COLOR_FBLK_WHITE "[6;37m" >NUL
        )
    )

:FBLK_YELLOW
    IF NOT DEFINED COLOR_FBLK_YELLOW (
        SET "COLOR_FBLK_YELLOW=[6;33m"
        REG QUERY "HKCU\Environment" /V COLOR_FBLK_YELLOW>NUL 2>&1
        IF ERRORLEVEL 1 (
            SETX COLOR_FBLK_YELLOW "[6;33m" >NUL
        )
    )

:FBLK_BRIGHTBLACK
    IF NOT DEFINED COLOR_FBLK_BRIGHTBLACK (
        SET "COLOR_FBLK_BRIGHTBLACK=[1;6;30m"
        REG QUERY "HKCU\Environment" /V COLOR_FBLK_BRIGHTBLACK>NUL 2>&1
        IF ERRORLEVEL 1 (
            SETX COLOR_FBLK_BRIGHTBLACK "[1;6;30m" >NUL
        )
    )

:FBLK_BRIGHTBLUE
    IF NOT DEFINED COLOR_FBLK_BRIGHTBLUE (
        SET "COLOR_FBLK_BRIGHTBLUE=[1;6;34m"
        REG QUERY "HKCU\Environment" /V COLOR_FBLK_BRIGHTBLUE>NUL 2>&1
        IF ERRORLEVEL 1 (
            SETX COLOR_FBLK_BRIGHTBLUE "[1;6;34m" >NUL
        )
    )

:FBLK_BRIGHTCYAN
    IF NOT DEFINED COLOR_FBLK_BRIGHTCYAN (
        SET "COLOR_FBLK_BRIGHTCYAN=[1;6;36m"
        REG QUERY "HKCU\Environment" /V COLOR_FBLK_BRIGHTCYAN>NUL 2>&1
        IF ERRORLEVEL 1 (
            SETX COLOR_FBLK_BRIGHTCYAN "[1;6;36m" >NUL
        )
    )

:FBLK_BRIGHTGREEN
    IF NOT DEFINED COLOR_FBLK_BRIGHTGREEN (
        SET "COLOR_FBLK_BRIGHTGREEN=[1;6;32m"
        REG QUERY "HKCU\Environment" /V COLOR_FBLK_BRIGHTGREEN>NUL 2>&1
        IF ERRORLEVEL 1 (
            SETX COLOR_FBLK_BRIGHTGREEN "[1;6;32m" >NUL
        )
    )

:FBLK_BRIGHTPURPLE
    IF NOT DEFINED COLOR_FBLK_BRIGHTPURPLE (
        SET "COLOR_FBLK_BRIGHTPURPLE=[1;6;35m"
        REG QUERY "HKCU\Environment" /V COLOR_FBLK_BRIGHTPURPLE>NUL 2>&1
        IF ERRORLEVEL 1 (
            SETX COLOR_FBLK_BRIGHTPURPLE "[1;6;35m" >NUL
        )
    )

:FBLK_BRIGHTRED
    IF NOT DEFINED COLOR_FBLK_BRIGHTRED (
        SET "COLOR_FBLK_BRIGHTRED=[1;6;31m"
        REG QUERY "HKCU\Environment" /V COLOR_FBLK_BRIGHTRED>NUL 2>&1
        IF ERRORLEVEL 1 (
            SETX COLOR_FBLK_BRIGHTRED "[1;6;31m" >NUL
        )
    )

:FBLK_BRIGHTWHITE
    IF NOT DEFINED COLOR_FBLK_BRIGHTWHITE (
        SET "COLOR_FBLK_BRIGHTWHITE=[1;6;37m"
        REG QUERY "HKCU\Environment" /V COLOR_FBLK_BRIGHTWHITE>NUL 2>&1
        IF ERRORLEVEL 1 (
            SETX COLOR_FBLK_BRIGHTWHITE "[1;6;37m" >NUL
        )
    )

:FBLK_BRIGHTYELLOW
    IF NOT DEFINED COLOR_FBLK_BRIGHTYELLOW (
        SET "COLOR_FBLK_BRIGHTYELLOW=[1;6;33m"
        REG QUERY "HKCU\Environment" /V COLOR_FBLK_BRIGHTYELLOW>NUL 2>&1
        IF ERRORLEVEL 1 (
            SETX COLOR_FBLK_BRIGHTYELLOW "[1;6;33m" >NUL
        )
    )

:SLB_BLACK
    IF NOT DEFINED COLOR_SLB_BLACK (
        SET "COLOR_SLB_BLACK=[5;30m"
        REG QUERY "HKCU\Environment" /V COLOR_SLB_BLACK>NUL 2>&1
        IF ERRORLEVEL 1 (
            SETX COLOR_SLB_BLACK "[5;30m" >NUL
        )
    )

:SLB_BLUE
    IF NOT DEFINED COLOR_SLB_BLUE (
        SET "COLOR_SLB_BLUE=[5;34m"
        REG QUERY "HKCU\Environment" /V COLOR_SLB_BLUE>NUL 2>&1
        IF ERRORLEVEL 1 (
            SETX COLOR_SLB_BLUE "[5;34m" >NUL
        )
    )

:SLB_CYAN
    IF NOT DEFINED COLOR_SLB_CYAN (
        SET "COLOR_SLB_CYAN=[5;36m"
        REG QUERY "HKCU\Environment" /V COLOR_SLB_CYAN>NUL 2>&1
        IF ERRORLEVEL 1 (
            SETX COLOR_SLB_CYAN "[5;36m" >NUL
        )
    )

:SLB_GREEN
    IF NOT DEFINED COLOR_SLB_GREEN (
        SET "COLOR_SLB_GREEN=[5;32m"
        REG QUERY "HKCU\Environment" /V COLOR_SLB_GREEN>NUL 2>&1
        IF ERRORLEVEL 1 (
            SETX COLOR_SLB_GREEN "[5;32m" >NUL
        )
    )

:SLB_PURPLE
    IF NOT DEFINED COLOR_SLB_PURPLE (
        SET "COLOR_SLB_PURPLE=[5;35m"
        REG QUERY "HKCU\Environment" /V COLOR_SLB_PURPLE>NUL 2>&1
        IF ERRORLEVEL 1 (
            SETX COLOR_SLB_PURPLE "[5;35m" >NUL
        )
    )

:SLB_RED
    IF NOT DEFINED COLOR_SLB_RED (
        SET "COLOR_SLB_RED=[5;31m"
        REG QUERY "HKCU\Environment" /V COLOR_SLB_RED>NUL 2>&1
        IF ERRORLEVEL 1 (
            SETX COLOR_SLB_RED "[5;31m" >NUL
        )
    )

:SLB_WHITE
    IF NOT DEFINED COLOR_SLB_WHITE (
        SET "COLOR_SLB_WHITE=[5;37m"
        REG QUERY "HKCU\Environment" /V COLOR_SLB_WHITE>NUL 2>&1
        IF ERRORLEVEL 1 (
            SETX COLOR_SLB_WHITE "[5;37m" >NUL
        )
    )

:SLB_YELLOW
    IF NOT DEFINED COLOR_SLB_YELLOW (
        SET "COLOR_SLB_YELLOW=[5;33m"
        REG QUERY "HKCU\Environment" /V COLOR_SLB_YELLOW>NUL 2>&1
        IF ERRORLEVEL 1 (
            SETX COLOR_SLB_YELLOW "[5;33m" >NUL
        )
    )

:SLB_BRIGHTBLACK
    IF NOT DEFINED COLOR_SLB_BRIGHTBLACK (
        SET "COLOR_SLB_BRIGHTBLACK=[1;5;30m"
        REG QUERY "HKCU\Environment" /V COLOR_SLB_BRIGHTBLACK>NUL 2>&1
        IF ERRORLEVEL 1 (
            SETX COLOR_SLB_BRIGHTBLACK "[1;5;30m" >NUL
        )
    )

:SLB_BRIGHTBLUE
    IF NOT DEFINED COLOR_SLB_BRIGHTBLUE (
        SET "COLOR_SLB_BRIGHTBLUE=[1;5;34m"
        REG QUERY "HKCU\Environment" /V COLOR_SLB_BRIGHTBLUE>NUL 2>&1
        IF ERRORLEVEL 1 (
            SETX COLOR_SLB_BRIGHTBLUE "[1;5;34m" >NUL
        )
    )

:SLB_BRIGHTCYAN
    IF NOT DEFINED COLOR_SLB_BRIGHTCYAN (
        SET "COLOR_SLB_BRIGHTCYAN=[1;5;36m"
        REG QUERY "HKCU\Environment" /V COLOR_SLB_BRIGHTCYAN>NUL 2>&1
        IF ERRORLEVEL 1 (
            SETX COLOR_SLB_BRIGHTCYAN "[1;5;36m" >NUL
        )
    )

:SLB_BRIGHTGREEN
    IF NOT DEFINED COLOR_SLB_BRIGHTGREEN (
        SET "COLOR_SLB_BRIGHTGREEN=[1;5;32m"
        REG QUERY "HKCU\Environment" /V COLOR_SLB_BRIGHTGREEN>NUL 2>&1
        IF ERRORLEVEL 1 (
            SETX COLOR_SLB_BRIGHTGREEN "[1;5;32m" >NUL
        )
    )

:SLB_BRIGHTPURPLE
    IF NOT DEFINED COLOR_SLB_BRIGHTPURPLE (
        SET "COLOR_SLB_BRIGHTPURPLE=[1;5;35m"
        REG QUERY "HKCU\Environment" /V COLOR_SLB_BRIGHTPURPLE>NUL 2>&1
        IF ERRORLEVEL 1 (
            SETX COLOR_SLB_BRIGHTPURPLE "[1;5;35m" >NUL
        )
    )

:SLB_BRIGHTRED
    IF NOT DEFINED COLOR_SLB_BRIGHTRED (
        SET "COLOR_SLB_BRIGHTRED=[1;5;31m"
        REG QUERY "HKCU\Environment" /V COLOR_SLB_BRIGHTRED>NUL 2>&1
        IF ERRORLEVEL 1 (
            SETX COLOR_SLB_BRIGHTRED "[1;5;31m" >NUL
        )
    )

:SLB_BRIGHTWHITE
    IF NOT DEFINED COLOR_SLB_BRIGHTWHITE (
        SET "COLOR_SLB_BRIGHTWHITE=[1;5;37m"
        REG QUERY "HKCU\Environment" /V COLOR_SLB_BRIGHTWHITE>NUL 2>&1
        IF ERRORLEVEL 1 (
            SETX COLOR_SLB_BRIGHTWHITE "[1;5;37m" >NUL
        )
    )

:SLB_BRIGHTYELLOW
    IF NOT DEFINED COLOR_SLB_BRIGHTYELLOW (
        SET "COLOR_SLB_BRIGHTYELLOW=[1;5;33m"
        REG QUERY "HKCU\Environment" /V COLOR_SLB_BRIGHTYELLOW>NUL 2>&1
        IF ERRORLEVEL 1 (
            SETX COLOR_SLB_BRIGHTYELLOW "[1;5;33m" >NUL
        )
    )

:BG_BLACK
    IF NOT DEFINED COLOR_BG_BLACK (
        SET "COLOR_BG_BLACK=[40m"
        REG QUERY "HKCU\Environment" /V COLOR_BG_BLACK>NUL 2>&1
        IF ERRORLEVEL 1 (
            SETX COLOR_BG_BLACK "[40m" >NUL
        )
    )

:BG_BLUE
    IF NOT DEFINED COLOR_BG_BLUE (
        SET "COLOR_BG_BLUE=[44m"
        REG QUERY "HKCU\Environment" /V COLOR_BG_BLUE>NUL 2>&1
        IF ERRORLEVEL 1 (
            SETX COLOR_BG_BLUE "[44m" >NUL
        )
    )

:BG_CYAN
    IF NOT DEFINED COLOR_BG_CYAN (
        SET "COLOR_BG_CYAN=[46m"
        REG QUERY "HKCU\Environment" /V COLOR_BG_CYAN>NUL 2>&1
        IF ERRORLEVEL 1 (
            SETX COLOR_BG_CYAN "[46m" >NUL
        )
    )

:BG_GREEN
    IF NOT DEFINED COLOR_BG_GREEN (
        SET "COLOR_BG_GREEN=[42m"
        REG QUERY "HKCU\Environment" /V COLOR_BG_GREEN>NUL 2>&1
        IF ERRORLEVEL 1 (
            SETX COLOR_BG_GREEN "[42m" >NUL
        )
    )

:BG_PURPLE
    IF NOT DEFINED COLOR_BG_PURPLE (
        SET "COLOR_BG_PURPLE=[45m"
        REG QUERY "HKCU\Environment" /V COLOR_BG_PURPLE>NUL 2>&1
        IF ERRORLEVEL 1 (
            SETX COLOR_BG_PURPLE "[45m" >NUL
        )
    )

:BG_RED
    IF NOT DEFINED COLOR_BG_RED (
        SET "COLOR_BG_RED=[41m"
        REG QUERY "HKCU\Environment" /V COLOR_BG_RED>NUL 2>&1
        IF ERRORLEVEL 1 (
            SETX COLOR_BG_RED "[41m" >NUL
        )
    )

:BG_BLK_RED
    IF NOT DEFINED COLOR_BG_BLK_RED (
        SET "COLOR_BG_BLK_RED=[1;5;41m"
        REG QUERY "HKCU\Environment" /V COLOR_BG_BLK_RED>NUL 2>&1
        IF ERRORLEVEL 1 (
            SETX COLOR_BG_BLK_RED "[1;5;41m" >NUL
        )
    )

:BG_BLK2_RED
    IF NOT DEFINED COLOR_BG_BLK2_RED (
        SET "COLOR_BG_BLK2_RED=[1;6;41m"
        REG QUERY "HKCU\Environment" /V COLOR_BG_BLK2_RED>NUL 2>&1
        IF ERRORLEVEL 1 (
            SETX COLOR_BG_BLK2_RED "[1;6;41m" >NUL
        )
    )

:BG_WHITE
    IF NOT DEFINED COLOR_BG_WHITE (
        SET "COLOR_BG_WHITE=[47m"
        REG QUERY "HKCU\Environment" /V COLOR_BG_WHITE>NUL 2>&1
        IF ERRORLEVEL 1 (
            SETX COLOR_BG_WHITE "[47m" >NUL
        )
    )

:BG_YELLOW
    IF NOT DEFINED COLOR_BG_YELLOW (
        SET "COLOR_BG_YELLOW=[43m"
        REG QUERY "HKCU\Environment" /V COLOR_BG_YELLOW>NUL 2>&1
        IF ERRORLEVEL 1 (
            SETX COLOR_BG_YELLOW "[43m" >NUL
        )
    )

:RESET
    IF NOT DEFINED COLOR_RESET (
        SET "COLOR_RESET=[0m"
        REG QUERY "HKCU\Environment" /V COLOR_RESET>NUL 2>&1
        IF ERRORLEVEL 1 (
            SETX COLOR_RESET "[0m" >NUL
        )
    )

:GEMS
    IF NOT DEFINED COLOR_GEMS (
        SET "COLOR_GEMS=%COLOR%38;2;209;69;255m"
        REG QUERY "HKCU\Environment" /V COLOR_GEMS>NUL 2>&1
        IF ERRORLEVEL 1 (
            SETX COLOR_GEMS "%COLOR%38;2;209;69;255m" >NUL
        )
    )

:AQUA
    IF NOT DEFINED COLOR_AQUA (
        SET "COLOR_AQUA=%COLOR%38;2;13;182;255m"
        REG QUERY "HKCU\Environment" /V COLOR_AQUA>NUL 2>&1
        IF ERRORLEVEL 1 (
            SETX COLOR_AQUA "%COLOR%38;2;13;182;255m" >NUL
        )
    )

:DARK_GRAY
    IF NOT DEFINED COLOR_DARK_GRAY (
        SET "COLOR_DARK_GRAY=%COLOR%38;2;100;100;100m"
        REG QUERY "HKCU\Environment" /V COLOR_DARK_GRAY>NUL 2>&1
        IF ERRORLEVEL 1 (
            SETX COLOR_DARK_GRAY "%COLOR%38;2;100;100;100m" >NUL
        )
    )

:GRAY
    IF NOT DEFINED COLOR_GRAY (
        SET "COLOR_GRAY=%COLOR%38;2;125;125;125m"
        REG QUERY "HKCU\Environment" /V COLOR_GRAY>NUL 2>&1
        IF ERRORLEVEL 1 (
            SETX COLOR_GRAY "%COLOR%38;2;125;125;125m" >NUL
        )
    )

:LIGHT_GRAY
    IF NOT DEFINED COLOR_LIGHT_GRAY (
        SET "COLOR_LIGHT_GRAY=%COLOR%38;2;150;150;150m"
        REG QUERY "HKCU\Environment" /V COLOR_LIGHT_GRAY>NUL 2>&1
        IF ERRORLEVEL 1 (
            SETX COLOR_LIGHT_GRAY "%COLOR%38;2;150;150;150m" >NUL
        )
    )

:DARK_GREEN
    IF NOT DEFINED COLOR_DARK_GREEN (
        SET "COLOR_DARK_GREEN=%COLOR%38;2;0;201;71m"
        REG QUERY "HKCU\Environment" /V COLOR_DARK_GREEN>NUL 2>&1
        IF ERRORLEVEL 1 (
            SETX COLOR_DARK_GREEN "%COLOR%38;2;0;201;71m" >NUL
        )
    )

:DEFAULT
    IF NOT DEFINED COLOR_DEFAULT (
        SET "COLOR_DEFAULT=%COLOR%38;2;200;200;200m"
        REG QUERY "HKCU\Environment" /V COLOR_DEFAULT>NUL 2>&1
        IF ERRORLEVEL 1 (
            SETX COLOR_DEFAULT "%COLOR%38;2;200;200;200m" >NUL
        )
    )

:ORANGE
    IF NOT DEFINED COLOR_ORANGE (
        SET "COLOR_ORANGE=%COLOR%38;2;252;129;3m"
        REG QUERY "HKCU\Environment" /V COLOR_ORANGE>NUL 2>&1
        IF ERRORLEVEL 1 (
            SETX COLOR_ORANGE "%COLOR%38;2;252;129;3m" >NUL
        )
    )

:BRIGHTORANGE
    IF NOT DEFINED COLOR_BRIGHTORANGE (
        SET "COLOR_BRIGHTORANGE=%COLOR%38;2;255;162;0m"
        REG QUERY "HKCU\Environment" /V COLOR_BRIGHTORANGE>NUL 2>&1
        IF ERRORLEVEL 1 (
            SETX COLOR_BRIGHTORANGE "%COLOR%38;2;255;162;0m" >NUL
        )
    )

:LOGO
    IF NOT DEFINED COLOR_LOGO (
        SET "COLOR_LOGO=%COLOR%38;2;0;227;57m"
        REG QUERY "HKCU\Environment" /V COLOR_LOGO>NUL 2>&1
        IF ERRORLEVEL 1 (
            SETX COLOR_LOGO "%COLOR%38;2;0;227;57m" >NUL
        )
    )

:BASICMINER
    IF NOT DEFINED COLOR_BASICMINER (
        SET "COLOR_BASICMINER=%COLOR%38;2;0;51;102m"
        REG QUERY "HKCU\Environment" /V COLOR_BASICMINER>NUL 2>&1
        IF ERRORLEVEL 1 (
            SETX COLOR_BASICMINER "%COLOR%38;2;0;51;102m" >NUL
        )
    )

:SILVERMINER
    IF NOT DEFINED COLOR_SILVERMINER (
        SET "COLOR_SILVERMINER=%COLOR%38;2;175;175;175m"
        REG QUERY "HKCU\Environment" /V COLOR_SILVERMINER>NUL 2>&1
        IF ERRORLEVEL 1 (
            SETX COLOR_SILVERMINER "%COLOR%38;2;175;175;175m" >NUL
        )
    )

:IRONMINER
    IF NOT DEFINED COLOR_IRONMINER (
        SET "COLOR_IRONMINER=%COLOR%38;2;165;156;148m"
        REG QUERY "HKCU\Environment" /V COLOR_IRONMINER>NUL 2>&1
        IF ERRORLEVEL 1 (
            SETX COLOR_IRONMINER "%COLOR%38;2;165;156;148m" >NUL
        )
    )

:GOLDMINER
    IF NOT DEFINED COLOR_GOLDMINER (
        SET "COLOR_GOLDMINER=%COLOR%38;2;203;161;53m"
        REG QUERY "HKCU\Environment" /V COLOR_GOLDMINER>NUL 2>&1
        IF ERRORLEVEL 1 (
            SETX COLOR_GOLDMINER "%COLOR%38;2;203;161;53m" >NUL
        )
    )

:COLOR_GOLDMINER_BLINK
    IF NOT DEFINED COLOR_GOLDMINER_BLINK (
        SET "COLOR_GOLDMINER_BLINK=CALL "%~f0" __COLOR_GOLDMINER_BLINK__"
        REG QUERY "HKCU\Environment" /V COLOR_GOLDMINER_BLINK>NUL 2>&1
        IF ERRORLEVEL 1 (
            SETX COLOR_GOLDMINER_BLINK "CALL \"%~f0\"__COLOR_GOLDMINER_BLINK__"
        )
    )

:DIAMONDMINER
    IF NOT DEFINED COLOR_DIAMONDMINER (
        SET "COLOR_DIAMONDMINER=%COLOR%38;2;63;208;224m"
        REG QUERY "HKCU\Environment" /V COLOR_DIAMONDMINER>NUL 2>&1
        IF ERRORLEVEL 1 (
            SETX COLOR_DIAMONDMINER "%COLOR%38;2;63;208;224m" >NUL
        )
    )

:EMERALDMINER
    IF NOT DEFINED COLOR_EMERALDMINER (
        SET "COLOR_EMERALDMINER=%COLOR%38;2;0;201;71m"
        REG QUERY "HKCU\Environment" /V COLOR_EMERALDMINER>NUL 2>&1
        IF ERRORLEVEL 1 (
            SETX COLOR_EMERALDMINER "%COLOR%38;2;0;201;71m" >NUL
        )
    )

:DARKMATTERMINER
    IF NOT DEFINED COLOR_DARKMATTERMINER (
        SET "COLOR_DARKMATTERMINER=%COLOR%38;2;118;64;255m"
        REG QUERY "HKCU\Environment" /V COLOR_DARKMATTERMINER>NUL 2>&1
        IF ERRORLEVEL 1 (
            SETX COLOR_DARKMATTERMINER "%COLOR%38;2;118;64;255m" >NUL
        )
    )
EXIT /B 0

:COLOR_GOLDMINER_BLINK_ROUTINE
    SETLOCAL DisableDelayedExpansion
    SET "BLINK_TEXT=%~2"
    IF NOT DEFINED BLINK_TEXT (
        ENDLOCAL
        EXIT /B 0
    )
    POWERSHELL.EXE -NoLogo -NoProfile -ExecutionPolicy Bypass -Command "$text=$env:BLINK_TEXT;$esc=[char]27;$gold=$esc+[38;2;203;161;53m;$reset=$esc+[0m;$x=[Console]::CursorLeft;$y=[Console]::CursorTop;for($i=0;$i -lt 6;$i++){[Console]::SetCursorPosition($x,$y);[Console]::Write($gold+$text+$reset);Start-Sleep -Milliseconds 150;[Console]::SetCursorPosition($x,$y);[Console]::Write( *$text.Length);Start-Sleep -Milliseconds 150};[Console]::SetCursorPosition($x,$y);[Console]::WriteLine($gold+$text+$reset)"
    ENDLOCAL
EXIT /B 0
